name: Pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Python para pre-commit
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Node para ESLint
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Instalar dependencias de ESLint
      - run: npm install --save-dev eslint @eslint/js globals

      # Ejecutar pre-commit
      - uses: pre-commit/action@v3.0.0
